### ISSUE TITLE
Architecture Template - arc42

### ISSUE THREAD

**Issue by koepalex** [OpenManufacturingPlatform/templates#1]
Shall we use arc42 as template for architecture documentation?

* [Template](https://arc42.org/download)
* [Github Repository](https://github.com/arc42/arc42-template)

**Comment by koepalex** [comment]
interessting, I'm not able to set the label "question" for this issue (¬_¬ )

**Comment by jpradocueva** [comment]
@koepalex I have changed the access to "TRIAGE" let me know if that works. Otherwise, we will have to use "WRITE" which in my opinion is dangerous to allocate "WRITE" access to everyone in the organization.

**Comment by koepalex** [comment]
@jpradocueva triage access was sufficient, thank you 👍

**Comment by jpradocueva** [comment]
👍 this is helping me to test "TRIAGE" access rights. GitHub introduced free private repos a couple of weeks ago and that has impacted the way I used to work. It is challenging to keep up with the Github changes.

**Comment by jpradocueva** [comment]
@koepalex , I will assign this issue to you for the time being. 
May I suggest that you a one page overview of how do you see it can be implemented and aligned with ["rules of engagement"](https://github.com/OpenManufacturingPlatform/rules_of_engagement#technical-specifications-development-phases)?

**Comment by BirgitBoss** [comment]
> 
> 
> Shall we use arc42 as template for architecture documentation?
> 
>     * [Template](https://arc42.org/download)
> 
>     * [Github Repository](https://github.com/arc42/arc42-template)

Hi Alex, of course I know arc42 - it is ok to start with. However, I would expect that the WG "Reference Architecture" defines which viewpoints are relevant for us a.s.o. (similar to IIRA in IIC). However, I am not sure whether there is already a common understanding of this.

Instead of arc24 just reference the IEC standard (ISO/IEC 42010 I think)

**Comment by jpradocueva** [comment]
@BirgitBoss @ Koepalex, how can we move forward this topic?

**Comment by koepalex** [comment]
I would suggest we follow Birgits advice and leave this topic (the decision) to the IoT Reference Architecture WG.

/cc @PickiHH

**Comment by jpradocueva** [comment]
This topic is closed now as there will be a discussion in the IoT Reference Architecture WG, once it is formed.
