### ISSUE TITLE
Use of Github Flavored Markdown syntax

### ISSUE THREAD

**Issue by koepalex** [OpenManufacturingPlatform/templates#3]
The current Templates are using HTML tables, instead of [Github Flavored Markdown Tables](https://help.github.com/en/github/writing-on-github/organizing-information-with-tables).

@jpradocueva is there a specific reason not to use Github Flavored Markdown? (e.g. issues with the document generators you mentioned)

**Comment by jpradocueva** [comment]
@koepalex yes, you are correct. 
Github Flavored Markdown Tables are very basic. There are some deficiencies that doesn't make it suitable for publication outside of GitHub:
* GitHub Flavored Markdown tables don't allow a table caption, therefore when converting the documents to PDF or HTML there are clear deficiencies (they are not listed in the index of tables or have a number). 
* Also, if the group wants to create tables where cells need to be merged then, GitHub Flavored Markdown cannot be used.
HTML is more complex to edit but we can have assistance to help the submitter: e.g. guidelines and for those who are using Visual Code there is the possibility to introduce extensions that pre-editing tables and other possible constructors.

**Questions**
* Do you think that we will have simple tables in our technical documents? 
* Do you foresee problems with HTML editing?

**Comment by koepalex** [comment]
From my point of view, we will have both simple and more complex tables. In the past merging of HTML tables, was never fun and took a lot of time, but the advantages you mentioned convinced me.

What is your favorit VS Code Extension for html tables?

**Comment by jpradocueva** [comment]
I have recently installed: https://marketplace.visualstudio.com/items?itemName=abusaidm.html-snippets
And I am developing an extension to be used with the constructors that are needed for the rendering engine MD2HTML, which converts  markdown to HTML and PDF.

**Comment by koepalex** [comment]
Thanks, the own vs code extensions sounds good. I like to test everything (end 2 end) this means up to the generated document locally before push the commits to the server.

If you need a beta tester, please let me know.

**Comment by jpradocueva** [comment]
Thank you! I will let you know, once it is completed.

**Comment by koepalex** [comment]
I will close the issue, @jpradocueva answered the question in his first comment.
